'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ALUGUEL
    Public Property ID_ALUGUEL As Integer
    Public Property cpf As String
    Public Property ID_CATALOGO As Nullable(Of Integer)
    Public Property data_aluguel As Nullable(Of Date)
    Public Property devolvido As Nullable(Of Boolean)

    Public Overridable Property CLIENTE As CLIENTE
    Public Overridable Property CATALOGO As CATALOGO
    Public Overridable Property DEVOLUCAOs As ICollection(Of DEVOLUCAO) = New HashSet(Of DEVOLUCAO)

End Class
