'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CATALOGO
    Public Property ID_CATALOGO As Integer
    Public Property NOME As String
    Public Property GENERO As String
    Public Property EAN As String
    Public Property QUANTIDADE As String

    Public Overridable Property ALUGUELs As ICollection(Of ALUGUEL) = New HashSet(Of ALUGUEL)

End Class
