'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class HumbertoLocadora
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=HumbertoLocadora")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property ALUGUELs() As DbSet(Of ALUGUEL)
    Public Overridable Property CATALOGOes() As DbSet(Of CATALOGO)
    Public Overridable Property CLIENTES() As DbSet(Of CLIENTE)
    Public Overridable Property DEVOLUCAOs() As DbSet(Of DEVOLUCAO)
    Public Overridable Property USUARIOs() As DbSet(Of USUARIO)
    Public Overridable Property tb_cep() As DbSet(Of tb_cep)

End Class
