'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DEVOLUCAO
    Public Property ID_DEVOLUCAO As Integer
    Public Property cpf As String
    Public Property ID_ALUGUEL As Nullable(Of Integer)

    Public Overridable Property ALUGUEL As ALUGUEL
    Public Overridable Property CLIENTE As CLIENTE

End Class
