'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tb_cep
    Public Property CEP As String
    Public Property ENDERECO As String
    Public Property CIDADE As String
    Public Property BAIRRO As String
    Public Property UF As String

End Class
