'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class USUARIO
    Public Property cpf As String
    Public Property data_nasc As String
    Public Property nome As String
    Public Property cep As String
    Public Property endereco As String
    Public Property comp As String
    Public Property bairro As String
    Public Property cidade As String
    Public Property uf As String
    Public Property fone_res As String
    Public Property celular As String
    Public Property email As String
    Public Property senha As String
    Public Property foto As String

End Class
